### ISSUE TITLE
网络环境较慢的情况下，虚拟机迁移失败

### ISSUE THREAD

**Issue by walteryang47** [eayun/ovirt-engine#24]
虚拟机迁移失败，失败之后虚拟机还是在源主机上运行。

#### 在 Event 事件栏里报错如下信息：
```
Migration failed due to Error: Migration not in progress (VM: fengkai, Source: hosted_engine_1, Destination: hosted_engine_2).
```
##### 日志：
* 源主机 vdsm 日志：
```
Thread-8053::WARNING::2015-04-08 15:46:09,503::migration::444::vm.Vm::(monitor_migration) vmId=`1ddf9258-0ae2-43d1-bd5d-55d2b016a113`::Migration is stuck: Hasn't progressed in 150.022356987 seconds. Aborting.
Thread-8053::DEBUG::2015-04-08 15:46:09,505::migration::469::vm.Vm::(stop) vmId=`1ddf9258-0ae2-43d1-bd5d-55d2b016a113`::stopping migration monitor thread
```
* 目标主机 vdsm 日志：
```
Thread-9105::DEBUG::2015-04-08 15:46:08,440::libvirtconnection::143::root::(wrapper) Unknown libvirterror: ecode: 42 edom: 10 level: 2 message: Domain not found: no domain with matching uuid '1ddf9258-0ae2-43d1-bd5d-55d2b016a113'
libvirtEventLoop::DEBUG::2015-04-08 15:46:08,441::resourceManager::198::Storage.ResourceManager.Request::(__init__) ResName=`Storage.b29aa258-2186-491f-9c04-02c6e9f8d34d`ReqID=`79216329-29c9-4c38-ab95-3ad3d5db72a3`::Request was made in '/usr/share/vdsm/storage/hsm.py' line '3262' at 'teardownImage'
libvirtEventLoop::DEBUG::2015-04-08 15:46:08,441::resourceManager::542::Storage.ResourceManager::(registerResource) Trying to register resource 'Storage.b29aa258-2186-491f-9c04-02c6e9f8d34d' for lock type 'shared'Thread-9105::ERROR::2015-04-08 15:46:08,440::vm::2340::vm.Vm::(_startUnderlyingVm) vmId=`1ddf9258-0ae2-43d1-bd5d-55d2b016a113`::Failed to start a migration destination vm
Traceback (most recent call last):
  File "/usr/share/vdsm/virt/vm.py", line 2313, in _startUnderlyingVm
    self._completeIncomingMigration()
  File "/usr/share/vdsm/virt/vm.py", line 4076, in _completeIncomingMigration
    self._incomingMigrationFinished.isSet(), usedTimeout)
  File "/usr/share/vdsm/virt/vm.py", line 4129, in _attachLibvirtDomainAfterMigration
    raise MigrationError(e.get_error_message()) 
MigrationError: Domain not found: no domain with matching uuid '1ddf9258-0ae2-43d1-bd5d-55d2b016a113'
```
* engine 日志：
```
2015-04-08 15:46:03,959 INFO  [org.ovirt.engine.core.vdsbroker.VdsUpdateRunTimeInfo] (DefaultQuartzScheduler_Worker-98) [53a6ab5d] RefreshVmList vm id 1ddf9258-0ae2-43d1-bd5d-55d2b016a113 is migrating to vds hosted_engine_2 ignoring it in the refresh until migration is done
2015-04-08 15:46:07,095 INFO  [org.ovirt.engine.core.vdsbroker.VdsUpdateRunTimeInfo] (DefaultQuartzScheduler_Worker-72) [222fd33c] RefreshVmList vm id 1ddf9258-0ae2-43d1-bd5d-55d2b016a113 is migrating to vds hosted_engine_2 ignoring it in the refresh until migration is done
2015-04-08 15:46:08,489 INFO  [org.ovirt.engine.core.vdsbroker.gluster.GlusterTasksListVDSCommand] (DefaultQuartzScheduler_Worker-71) [48c4b64a] START, GlusterTasksListVDSCommand(HostName = Host_199, HostId = dc27c924-96c9-4213-8ed2-fb110306124c), log id: 3e19bc15
2015-04-08 15:46:08,546 INFO  [org.ovirt.engine.core.vdsbroker.gluster.GlusterTasksListVDSCommand] (DefaultQuartzScheduler_Worker-71) [48c4b64a] FINISH, GlusterTasksListVDSCommand, return: [], log id: 3e19bc15
2015-04-08 15:46:09,946 INFO  [org.ovirt.engine.core.vdsbroker.VdsUpdateRunTimeInfo] (DefaultQuartzScheduler_Worker-93) [30a0d701] VM fengkai 1ddf9258-0ae2-43d1-bd5d-55d2b016a113 moved from MigratingFrom --> Up
2015-04-08 15:46:09,947 INFO  [org.ovirt.engine.core.vdsbroker.VdsUpdateRunTimeInfo] (DefaultQuartzScheduler_Worker-93) [30a0d701] Adding VM 1ddf9258-0ae2-43d1-bd5d-55d2b016a113 to re-run list
2015-04-08 15:46:10,116 ERROR [org.ovirt.engine.core.vdsbroker.VdsUpdateRunTimeInfo] (DefaultQuartzScheduler_Worker-93) [30a0d701] Rerun vm 1ddf9258-0ae2-43d1-bd5d-55d2b016a113. Called from vds hosted_engine_1
2015-04-08 15:46:10,145 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] START, MigrateStatusVDSCommand(HostName = hosted_engine_1, HostId = efbfbde0-539b-472d-adb0-4ceb92e28e30, vmId=1ddf9258-0ae2-43d1-bd5d-55d2b016a113), log id: 258ceca6
2015-04-08 15:46:10,148 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] Failed in MigrateStatusVDS method
2015-04-08 15:46:10,149 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] Command org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand return value 
 StatusOnlyReturnForXmlRpc [mStatus=StatusForXmlRpc [mCode=47, mMessage=Migration canceled]]
2015-04-08 15:46:10,149 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] HostName = hosted_engine_1
2015-04-08 15:46:10,150 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] Command MigrateStatusVDSCommand(HostName = hosted_engine_1, HostId = efbfbde0-539b-472d-adb0-4ceb92e28e30, vmId=1ddf9258-0ae2-43d1-bd5d-55d2b016a113) execution failed. Exception: VDSErrorException: VDSGenericException: VDSErrorException: Failed to MigrateStatusVDS, error = Migration canceled, code = 47
2015-04-08 15:46:10,151 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.MigrateStatusVDSCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] FINISH, MigrateStatusVDSCommand, log id: 258ceca6
2015-04-08 15:46:10,249 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (org.ovirt.thread.pool-8-thread-41) [30a0d701] Correlation ID: 250247d5, Job ID: 37d19127-764b-4ab1-bfe9-6424cf871e8b, Call Stack: null, Custom Event ID: -1, Message: Migration failed due to Error: Migration not in progress (VM: fengkai, Source: hosted_engine_1, Destination: hosted_engine_2).
2015-04-08 15:46:10,358 INFO  [org.ovirt.engine.core.bll.MigrateVmToServerCommand] (org.ovirt.thread.pool-8-thread-41) [30a0d701] Lock freed to object EngineLock [exclusiveLocks= key: 1ddf9258-0ae2-43d1-bd5d-55d2b016a113 value: VM
, sharedLocks= ] 
```

**Comment by walteryang47** [comment]
通过查看源主机的 vdsm 日志发现如下信息：
```Migration is stuck: Hasn't progressed in 150.022356987 seconds. Aborting.```
说明是超时引起。
在源主机上的设置如下配置文件```/etc/vdsm/vdsm.conf```：
在 ```[vars]``` 下增加配置项：
```migration_progress_timeout = 3000```
问题解决。

**Comment by walteryang47** [comment]
如果网络较慢， [vars] 下的 migration_max_time_per_gib_mem 参数也可适当调大， 默认是 64
